server:
  port: 8080

spring:
  datasource:
    username: root
    password: Root_123
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp





#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.banyuan.tankproject.domain

#showSql
#logging:
#  level:
#    com:
#      example:
#        mapper : debug

